//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.roodapps.ispy.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 327e107b-ba1a-4f18-b689-594f09b3689b aws-my-sample-app-android-v0.15";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("ap-southeast-2");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "ap-southeast-2:25ffcacf-9902-4151-bd93-bb508fd321f0";
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("ap-southeast-2");
}
